export const TR_CITIES = [
  'Adana',
  'Ankara',
  'Antalya',
  'Aydın',
  'Balıkesir',
  'Bursa',
  'Denizli',
  'Eskişehir',
  'Gaziantep',
  'Hatay',
  'İstanbul',
  'İzmir',
  'Kocaeli',
  'Konya',
  'Manisa',
  'Mersin',
  'Muğla',
  'Sakarya',
  'Samsun',
  'Tekirdağ'
] as const;

export const TR_CITY_DISTRICTS: Record<string, string[]> = {
  Adana: ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Ceyhan'],
  Ankara: ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan'],
  Antalya: ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Aksu', 'Alanya'],
  Aydın: ['Efeler', 'Kuşadası', 'Didim', 'Nazilli', 'Söke'],
  Balıkesir: ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Ayvalık'],
  Bursa: ['Osmangazi', 'Nilüfer', 'Yıldırım', 'Gemlik', 'İnegöl'],
  Denizli: ['Pamukkale', 'Merkezefendi', 'Çivril', 'Acıpayam'],
  Eskişehir: ['Odunpazarı', 'Tepebaşı', 'Sivrihisar'],
  Gaziantep: ['Şahinbey', 'Şehitkamil', 'Nizip'],
  Hatay: ['Antakya', 'İskenderun', 'Defne', 'Dörtyol'],
  İstanbul: ['Adalar', 'Arnavutköy', 'Ataşehir', 'Avcılar', 'Bağcılar', 'Bahçelievler', 'Bakırköy', 'Başakşehir', 'Bayrampaşa', 'Beşiktaş', 'Beykoz', 'Beylikdüzü', 'Beyoğlu', 'Büyükçekmece', 'Çekmeköy', 'Esenler', 'Esenyurt', 'Eyüpsultan', 'Fatih', 'Gaziosmanpaşa', 'Güngören', 'Kadıköy', 'Kağıthane', 'Kartal', 'Küçükçekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sarıyer', 'Silivri', 'Sultanbeyli', 'Sultangazi', 'Şile', 'Şişli', 'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu'],
  İzmir: ['Konak', 'Karşıyaka', 'Bornova', 'Bayraklı', 'Buca', 'Çiğli', 'Gaziemir'],
  Kocaeli: ['İzmit', 'Gebze', 'Darıca', 'Başiskele', 'Kartepe'],
  Konya: ['Selçuklu', 'Meram', 'Karatay', 'Ereğli'],
  Manisa: ['Yunusemre', 'Şehzadeler', 'Akhisar', 'Turgutlu'],
  Mersin: ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus'],
  Muğla: ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas'],
  Sakarya: ['Adapazarı', 'Serdivan', 'Erenler', 'Akyazı'],
  Samsun: ['İlkadım', 'Atakum', 'Canik', 'Bafra'],
  Tekirdağ: ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Kapaklı']
};
