#!/usr/bin/env node

const API_URL = process.env.TASKS_SMOKE_API_URL ?? 'http://localhost:4000';
const EMAIL = (process.env.TASKS_SMOKE_EMAIL ?? process.env.SEED_PLATFORM_ADMIN_EMAIL ?? 'admin@themonocore.com').toLowerCase();
const PASSWORD = process.env.TASKS_SMOKE_PASSWORD ?? process.env.SEED_PLATFORM_ADMIN_PASSWORD ?? 'ChangeMe123!';
const COMPANY_ID = process.env.TASKS_SMOKE_COMPANY_ID ?? '00000000-0000-0000-0000-000000000001';

function fail(message, detail) {
  console.error(JSON.stringify({ ok: false, message, detail }, null, 2));
  process.exit(1);
}

function assert(condition, message, detail) {
  if (!condition) fail(message, detail);
}

function parseCookies(setCookieHeaders) {
  const cookies = {};
  for (const item of setCookieHeaders) {
    const [pair] = item.split(';');
    const [name, value] = pair.split('=');
    if (name && value) cookies[name.trim()] = value.trim();
  }
  return cookies;
}

async function request(path, options = {}, auth = null) {
  const headers = new Headers(options.headers || {});
  headers.set('Content-Type', 'application/json');

  if (auth) {
    headers.set('x-company-id', COMPANY_ID);
    headers.set('x-csrf-token', auth.csrfToken);
    headers.set('Cookie', `session_token=${auth.sessionToken}; csrf_token=${auth.csrfToken}`);
  }

  const response = await fetch(`${API_URL}${path}`, {
    ...options,
    headers
  });

  if (!response.ok) {
    const body = await response.text();
    fail(`Request failed: ${path}`, { status: response.status, body });
  }

  const text = await response.text();
  return text ? JSON.parse(text) : null;
}

async function login() {
  const res = await fetch(`${API_URL}/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email: EMAIL, password: PASSWORD })
  });

  if (!res.ok) {
    fail('Login failed', { status: res.status, body: await res.text() });
  }

  const setCookie = res.headers.getSetCookie?.() ?? [];
  const parsed = parseCookies(setCookie);
  const sessionToken = parsed.session_token;
  const csrfToken = parsed.csrf_token;

  assert(Boolean(sessionToken), 'Missing session_token from login cookies');
  assert(Boolean(csrfToken), 'Missing csrf_token from login cookies');

  return { sessionToken, csrfToken };
}

function ymd(date) {
  return date.toISOString().slice(0, 10);
}

async function main() {
  const auth = await login();
  const nonce = Date.now().toString().slice(-8);
  const today = new Date();
  const to = new Date(today.getTime() + 6 * 24 * 60 * 60 * 1000);

  const roles = await request('/app-api/roles', { method: 'GET' }, auth);
  const owner = Array.isArray(roles) ? roles.find((row) => row.key === 'owner') : null;
  assert(Boolean(owner?.id), 'Owner role is required for task smoke test');

  const template = await request(
    '/app-api/tasks/templates',
    {
      method: 'POST',
      body: JSON.stringify({
        title: `Smoke Daily Task ${nonce}`,
        description: 'Generated by smoke test',
        priority: 'NORMAL',
        scheduleType: 'DAILY',
        scheduleMeta: null,
        defaultAssigneeType: 'ROLE',
        defaultAssigneeRoleId: owner.id
      })
    },
    auth
  );

  const rangeFrom = ymd(today);
  const rangeTo = ymd(to);
  const firstRun = await request(`/app-api/tasks/generate?from=${rangeFrom}&to=${rangeTo}`, { method: 'POST', body: '{}' }, auth);
  const secondRun = await request(`/app-api/tasks/generate?from=${rangeFrom}&to=${rangeTo}`, { method: 'POST', body: '{}' }, auth);

  assert(firstRun.generatedCount > 0, 'Expected generator to create task instances', firstRun);
  assert(secondRun.generatedCount === 0, 'Task generation must be idempotent for same range', secondRun);

  const tasks = await request(
    `/app-api/tasks?from=${rangeFrom}&to=${rangeTo}&assigneeRoleId=${owner.id}`,
    { method: 'GET' },
    auth
  );
  assert(Array.isArray(tasks) && tasks.length > 0, 'Generated tasks should be queryable');

  const firstTask = tasks[0];
  await request(`/app-api/tasks/${firstTask.id}/complete`, { method: 'POST', body: '{}' }, auth);

  const summary = await request(`/app-api/tasks/reports/summary?from=${rangeFrom}&to=${rangeTo}`, { method: 'GET' }, auth);
  assert(Number(summary.done) >= 1, 'Summary report should include completed task count', summary);

  console.log(
    JSON.stringify(
      {
        ok: true,
        templateId: template.id,
        generatedFirstRun: firstRun.generatedCount,
        generatedSecondRun: secondRun.generatedCount,
        completedTaskId: firstTask.id,
        reportDoneCount: summary.done
      },
      null,
      2
    )
  );
}

main().catch((error) => fail('Unexpected tasks smoke failure', { message: error?.message, stack: error?.stack }));
